//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_b
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bestelling
    {
        public int BestellingID { get; set; }
        public Nullable<System.DateTime> DatumOpgemaakt { get; set; }
        public Nullable<int> PersoneelslidID { get; set; }
        public Nullable<int> LeverancierID { get; set; }
        public Nullable<int> KlantID { get; set; }
    }
}
