//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_b
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klant
    {
        public int KlantId { get; set; }
        public string Voornaam { get; set; }
        public string Achternaam { get; set; }
        public string Straatnaam { get; set; }
        public byte[] Huisnummer { get; set; }
        public byte[] Postcode { get; set; }
        public string Gemeente { get; set; }
        public string Telefonnummer { get; set; }
        public string Emailadress { get; set; }
        public Nullable<System.DateTime> AangemaktOp { get; set; }
        public string Opmerking { get; set; }
    }
}
