//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse_b
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leverancier
    {
        public int LeverancierId { get; set; }
        public string Contactpersoon { get; set; }
        public Nullable<decimal> Telefonnummer { get; set; }
        public string Emailadress { get; set; }
        public string Straatnaam { get; set; }
        public Nullable<decimal> Huisnummer { get; set; }
        public Nullable<decimal> Bus { get; set; }
        public string Postcode { get; set; }
        public string Gemeente { get; set; }
    }
}
